### ISSUE TITLE
Accessing normalized & weighted result

### ISSUE THREAD

**Issue by angaik** [GreenDelta/olca-ipc.py#23]
How to access the result obtained after using the predefined normalization & weighting set? Currently, I can only access the results for impact categories (using 'result.impact_results' code line)

**Comment by msrocka** [comment]
This is available since some time now with the two methods `get_normalized_impacts` and `get_weighted_impacts`. I added examples to the documentation:

+ https://greendelta.github.io/openLCA-ApiDoc/results/impacts/normalized.html#olca-ipcpy
+ https://greendelta.github.io/openLCA-ApiDoc/results/impacts/weighted.html#olca-ipcpy

you may have to update your local version.
